apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minikube-react-app
  template:
    metadata:
      labels:
        app: minikube-react-app
    spec:
      containers:
        - name: minikube-react-app
          image: dvelez100/minikube-react-app:v3
          ports:
            - containerPort: 80
